### PR TITLE
Clean space and tab at eol in game files

### PR DESCRIPTION
**Pull request by xoddark**
Hello,
this change just remove the space and tab at the end of line in file from src/game.

If it's interest you I can do this for other src subfolder.

### CODE REVIEW

**Comment by Eli2** [comment]
Please check the style guide before working on the style.
The tabs in "empty" lines are intentional.
http://wiki.arx-libertatis.org/Code_Style_Guide#Indentation

**Comment by xoddark** [comment]
Ooops sorry, I misunderstand some change done by Daniel Scharrer on my first pull request.
Do you interested by the remove of the space at end of line ?

**Comment by xoddark** [comment]
Change like in this change : https://github.com/xoddark/ArxLibertatis/commit/11043101a95cdc5ac187e3f4ff044b57661df0ab

**Comment by dscharrer** [comment]
Yes, trailing spaces that are not part of the indentation should be removed.

**Pull request closed without merging**
