### PR TITLE
Fixed isfinite check

### PR DESCRIPTION
**Pull request by justnope**
Fixed isallfinite check. The not operator "!" was removed.

### CODE REVIEW

**Comment by Gussak** [comment]
could you re-open yours?
mine was created with not good commit messagage, see what I wrote there..
I will close mine.
thx!

**Comment by Gussak** [comment]
Whenever I try to amend a commit in git-gui, when I try to push to github, it says something about fast forward, wont work, then I have to merge/overwrite locally I think to fix the fast forward thing (I dont even understand what that means).. I am a bit tired, too late here, but is something like that. So the owner fixing it would be the best option I guess.

**Comment by Gussak** [comment]
> When you amend your commit message, you need to _force_ push the changes. In git-gui, if I remember correctly, there's a checkbox at the bottom which says "Force blabla...". Tick that one and then push the changes and this should work

there is: "force overwrite existing branch (may discard changes)", it is certainly that, I will try it next time, thx!!

**Comment by dscharrer** [comment]
Thanks.

**Pull request merged**
