### PR TITLE
Refactor: Small tweaks for consistent formatting

### PR DESCRIPTION
**Pull request by meszaros-lajos-gyorgy**
- [x] Add missing curly brackets for ifs and loops
- [x] Unnest nested ifs
- [x] Add missing indentation
- [x] Split single if-return lines into if blocks

### CODE REVIEW

**Comment by bsxf-47** [comment]
Maybe squash the missing `if` back to where you made that mistake? Plus for debugging purposes it's better to have every commit be able to build if possible.

**Comment by meszaros-lajos-gyorgy** [comment]
> Maybe squash the missing `if` back to where you made that mistake? Plus for debugging purposes it's better to have every commit be able to build if possible.

Github offers an option to squash merge the pull request instead of merging the individual commits, so this should be fine. Dscharrer did so in my last PR: https://github.com/arx/ArxLibertatis/pull/279

**Comment by dscharrer** [comment]
While the changes are mostly good, giant commits like these take really long to review. Even more so if they mix different kind of changes. They also make it harder to bisect issues later if they end up adding bugs. Commits are cheap so keep them smaller please. For style fixes and simple refactors its OK to group changes for one file (or perhaps a couple if  there are not to many lines changed) in one commit. But anything touching the whole project at once should really come in the form of a tool (e.g. a Clang-Tidy config) that generates those changes to make it reviewable.

It's also generally not good to just arbitrarily change line breaks and the number of empty lines for code that you aren't making other changes too as those are a) don't have an obvious correct formatting and b) changing them still makes it harder to cherry-pick other fixes to older versions. Those kind of changes are OK if its for code you are changing for another reason or if the goal is to use an auto-formatter at some point but otherwise are just noise. Adding braces for single-statement ifs and missing indentation for empty lines on the other hand are more clearly correct.

As bsxf-47 said, commits that fix issues with previous commits should be squashed so that each commit builds and runs. I can do that manually but if those fixes also are mixed with a bunch of other changes that takes a lot more work. And squashing everything just makes the commits even larger.

**Comment by meszaros-lajos-gyorgy** [comment]
okay, then I'll create a smaller commit later

**Pull request closed without merging**
