### PR TITLE
Some Flying Eye refactors

### PR DESCRIPTION
**Pull request by bsxf-47**
Attempted to encapsulate eyeball code so that other code doesn't change its variables on the go, plus some minor tweaks to Interface code.

### CODE REVIEW

**Review by dscharrer — CHANGES_REQUESTED** [review]
This changes the collision check from the desired position to the current position. This means you can walk into walls for one frame and then get stuck there until the spell ends.

**Comment by bsxf-47** [comment]
I'll look into that commit though while testing it I could've sworn I was getting stuck on things either way. Worst case scenario I'll just remove it. 
I'll go through the code to find the style issues, thought I had found them all.
As for the frame dependent disappearing I posted a question on IRC about it but got no reply so I decided to let it be for now. The question was basically how long should the disappearing take? Appearing takes 3 seconds, should that be the same?

**Comment by dscharrer** [comment]
Ah, sorry, missed your question in IRC. I think it currently progresses 1% per frame. 3s would match that at 33 FPS so it's probably alright.

**Comment by bsxf-47** [comment]
I believe I have hunted down all the style issues. Reverted the offending commit, added one more in turn, that is [feb57e8](https://github.com/arx/ArxLibertatis/pull/277/commits/feb57e8a5b26d33484997e062a777db69cc15108).

**Comment by dscharrer** [comment]
Thanks.

**Pull request merged**
